### PR TITLE
handle basePath option for preprocessors paths

### LINKED ISSUE #146: 0.10.x breaks ng-html2js-preprocessor
Just tried updating to 0.10.0 / 0.10.1 from 0.8.3 which fail to work as I'm using [ng-html2js-preprocessor](https://github.com/karma-runner/karma-ng-html2js-preprocessor).

Rolling back to 0.9.0 works correctly as per 0.8.x behaviour.

I'm not entirely sure what's going on, but I think it is something to do with this commit: @a10aaa7548267ab035f8f4689eb54b2ead9245ef

If I specify preprocessors in my grunt config:
```js
preprocessors: {
     'modules/**/*.js': ['coverage'],
     'modules/**/*.html': ['ng-html2js']
},
```

The template loading in my tests fails (the preprocessor is supposed to load templates into an Angular module) and therefore a bunch of my tests break.

If I specify the above preprocessors in my Karma config, it works correctly, so I suspect there is something wrong with the above commit.

### PR DESCRIPTION
**Pull request by ValentinH**
fix: handle basePath option for preprocessors paths

Closes #146

### CODE REVIEW

**Comment by ValentinH** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Comment by ValentinH** [comment]
When will it be released?

**Comment by dignifiedquire** [comment]
Now as `2.0.0`

**Comment by ValentinH** [comment]
\o/ Just for my knowledge, why 2.0.0

**Comment by dignifiedquire** [comment]
Because while it is a bug fix it's technically a breaking change to the behaviour in `1.0.0` so I went with a full major upgrade

**Comment by ValentinH** [comment]
Sounds good!

**Pull request merged**
