### PR TITLE
bump peerDep

### PR DESCRIPTION
**Pull request by vladikoff**
Ref https://github.com/gruntjs/grunt-docs/blob/master/Blog-2016-02-11-Grunt-1.0.0-rc1-released.md#peer-dependencies

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Thanks could you change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) please?

**Comment by vladikoff** [comment]
Updated! Thanks!

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Comment by porjo** [comment]
I'm confused. Didn't this change get merged into master....and yet current master does not have it!?

**Pull request merged**
